config/routes.rb
Rails.application.routes.draw do
  resources :deployments

  resources :projects

  resources :providers

  root :to => 'home#index'
end

app/models/deployment.rb
class Deployment < ActiveRecord::Base
  include Elasticsearch::Model

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :deployments

  def to_tf
    body
  end
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  serialize :configuration

  self.inheritance_column = nil

  def configuration=(value)
    if value.kind_of? String
      super(YAML.load(value))
    end
  end

  def to_tf
    to_h.to_json
  end

  def to_h
    { "provider" => { type => configuration } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deployments_controller.rb
class DeploymentsController < ApplicationController
  before_action :set_deployment, only: [:show, :edit, :update, :destroy]

  # GET /deployments
  # GET /deployments.json
  def index
    @deployments = Deployment.all
  end

  # GET /deployments/1
  # GET /deployments/1.json
  def show
  end

  # GET /deployments/new
  def new
    @deployment = Deployment.new
  end

  # GET /deployments/1/edit
  def edit
  end

  # POST /deployments
  # POST /deployments.json
  def create
    @deployment = Deployment.new(deployment_params)

    respond_to do |format|
      if @deployment.save
        TerraformApplyWorker.perform_async(@deployment.id)
        format.html { redirect_to @deployment, notice: 'Deployment was successfully created.' }
        format.json { render :show, status: :created, location: @deployment }
      else
        format.html { render :new }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deployments/1
  # PATCH/PUT /deployments/1.json
  def update
    respond_to do |format|
      if @deployment.update(deployment_params)
        TerraformApplyWorker.perform_async(@deployment.id)
        format.html { redirect_to @deployment, notice: 'Deployment was successfully updated.' }
        format.json { render :show, status: :ok, location: @deployment }
      else
        format.html { render :edit }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deployments/1
  # DELETE /deployments/1.json
  def destroy
    #@deployment.destroy
    TerraformApplyWorker.perform_async(@deployment.id, true)
    respond_to do |format|
      format.html { redirect_to deployments_url, notice: 'Deployment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deployment
      @deployment = Deployment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deployment_params
      params.require(:deployment).permit(:name, :project_id, :variables, :output, :status, :state)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :body, :status, :state)
    end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :type, :configuration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deployments_helper.rb
module DeploymentsHelper
  def deployment_status(state)
    if state.to_s.empty?
      "unknown"
    elsif state == 0
      "pending"
    elsif state == 1
      content_tag :span, 'running', class: 'label label-success'
    elsif state == 128
      content_tag :span, 'idle', class: 'label label-default'
    elsif state == 255
      content_tag :span, 'failed', class: 'label label-danger'
    else
      "???"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/deployments/_form.html.erb
<%= form_for(@deployment) do |f| %>
  <% if @deployment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deployment.errors.count, "error") %> prohibited this deployment from being saved:</h2>

      <ul>
      <% @deployment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.collection_select(:project_id, Project.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :variables %><br>
    <%= f.text_area :variables %>
  </div>
  <div class="field">
    <%= f.label :output %><br>
    <%= f.text_area :output %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deployments/edit.html.erb
<h1>Editing Deployment</h1>

<%= render 'form' %>

<%= link_to 'Show', @deployment %> |
<%= link_to 'Back', deployments_path %>

app/views/deployments/index.html.erb
<h1>Deployments</h1>

<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'New Deployment', new_deployment_path, class: 'btn btn-default' %>
</p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deployments.each do |deployment| %>
      <tr>
        <td><%= deployment.name %></td>
        <td><%= deployment.project_id %></td>
        <td><%= deployment_status(deployment.status) %></td>
        <td><%= link_to 'Show', deployment %></td>
        <td><%= link_to 'Edit', edit_deployment_path(deployment) %></td>
        <td><%= link_to 'Destroy', deployment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/deployments/new.html.erb
<h1>New Deployment</h1>

<%= render 'form' %>

<%= link_to 'Back', deployments_path %>

app/views/deployments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deployment.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @deployment.project_id %>
</p>

<p>
  <strong>Variables:</strong>
  <%= @deployment.variables %>
</p>

<p>
  <strong>Output:</strong>
  <%= @deployment.output %>
</p>

<p>
  <strong>Status:</strong>
  <%= @deployment.status %>
</p>

<p>
  <strong>State:</strong>
  <%= @deployment.state %>
</p>

<%= link_to 'Edit', edit_deployment_path(@deployment) %> |
<%= link_to 'Back', deployments_path %>

app/views/home/index.html.erb
<h1>Appian</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appian</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Appian</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/providers">Providers</a></li>
          <li><a href="/projects">Projects</a></li>
          <li><a href="/deployments">Deployments</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, cols: "80", rows: "25" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'New Project', new_project_path, class: 'btn btn-default' %>
</p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td>
          <%= link_to 'Show', project %>
          <%= link_to 'Edit', edit_project_path(project) %>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Body:</strong>
  <pre><%= @project.body %></pre>
</p>

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :configuration %><br>
    <%= f.text_area :configuration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Providers</h1>

<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'New Provider', new_provider_path, class: 'btn btn-default' %>
</p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Configuration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.type %></td>
        <td><%= provider.configuration %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @provider.type %>
</p>

<p>
  <strong>Configuration:</strong>
  <%= @provider.configuration %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>